version: '2'
volumes:
  mysql:
    driver: 'local'
services:
  wordpress:
    build: .
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - .:/var/www/html
    depends_on:
      - wordpress
  cli:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
      - ./bin/docker_wp_cli:/bin/docker_wp_cli
    command: /bin/docker_wp_cli
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
volumes:
  db_data:
